= Parameters

The parent key for all of the following parameters is `mariadb_operator`.

== `namespace`

[horizontal]
type:: string
default:: `syn-mariadb-operator`

The namespace in which to deploy this component.

== `images.(mariadb|mariadb_operator).registry`

[horizontal]
type:: string
default:: `see class/defaults.yml`

The image registry used for the container image path.

== `images.(mariadb|mariadb_operator).repository`

[horizontal]
type:: string
default:: `see class/defaults.yml`

The image repository used for the container image path.

== `images.(mariadb|mariadb_operator).tag`

[horizontal]
type:: string
default:: `see class/defaults.yml`

The image tag used for the container image path.

== `helmValues`

[horizontal]
type:: dict
default:: `see class/defaults.yml`

All helmValues are passed to the helm chart. This allows to configure all https://github.com/mariadb-operator/mariadb-operator/tree/main/deploy/charts/mariadb-operator#values[mariadb-operator helm chart values].

== Example

[source,yaml]
----
parameters:
  mariadb_operator:
    images:
      mariadb_operator:
        tag: 25.10.2
      mariadb:
        tag: 11.8.5
----
